apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itsmevara13/proj1.git
    targetRevision: HEAD
    path: .                          # watch the whole repo root
    directory:
    recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: proj1-gitops
  syncPolicy:
    automated:
      prune: true                    # delete resources removed from Git
      selfHeal: true                 # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
